version: '3'
services:
  sftp:
    image: atmoz/sftp
    ports:
      - "22"
    environment:
      SFTP_USERS: testuser:password:100:100:download
    volumes:
      - '${{ github.workspace }}/tests/files/keys/user_rsa:/home/ledgerpigeon/.ssh/authorized_keys'
      - '${{ github.workspace }}/tests/files/keys/user_rsa.pub:/home/ledgerpigeon/.ssh/user_rsa.pub'    

  localstack:
    image: localstack/localstack:2.0
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - REGION=us-east-1
      - BUCKET_NAME_INCOMING=tb-ledgerpigeon-integration
    ports:
      - "4566"
    volumes:
      - '${{ github.workspace }}/tests/files/localstack/localstack-script.sh:/etc/localstack/init/ready.d/script.sh'
      - '${{ github.workspace }}/tests/files/keys/user_rsa:/tmp/ssh/user_rsa'
      - '${{ github.workspace }}/tests/files/localstack/bank1:/tmp/bank1'
