version: '3'
services:
  sftp:
    image: atmoz/sftp
    ports:
      - "22"
    environment:
      SFTP_USERS: testuser:password:100:100:download
    volumes:
      - './tests/files/keys/foo:/home/ledgerpigeon/.ssh/authorized_keys'
      - './tests/files/keys/foo.pub:/home/ledgerpigeon/.ssh/user_rsa.pub'    

  localstack:
    image: localstack/localstack:2.0
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - REGION=us-east-1
      - BUCKET_NAME_INCOMING=tb-ledgerpigeon-integration
    ports:
      - "4566"
